### ISSUE TITLE
[BUG] File upload issue

### ISSUE THREAD

**Issue by stijnb1234** [MinnDevelopment/discord-webhooks#27]
When I try to upload a file to Discord using a webhook, which includes an embed, I get this error:
```
Could not pass event AFRenderEvent to ActionFoto v2.7.3
java.lang.NoSuchMethodError: okhttp3.MultipartBody.appendQuotedString(Ljava/lang/StringBuilder;Ljava/lang/String;)V
    at okhttp3.MultipartBody$Part.createFormData(MultipartBody.java:251) ~[?:?]
    at okhttp3.MultipartBody$Builder.addFormDataPart(MultipartBody.java:327) ~[?:?]
    at club.minnced.discord.webhook.send.WebhookMessage.getBody(WebhookMessage.java:328) ~[?:?]
    at club.minnced.discord.webhook.WebhookClient.send(WebhookClient.java:217) ~[?:?]
    at nl.sbdeveloper.actionfoto.listeners.ActionFotoTakeListener.onActionFotoTake(ActionFotoTakeListener.java:68) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor294.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-457]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
    at nl.sbdeveloper.actionfoto.api.FrameAPI.lambda$renderAFFrame$2(FrameAPI.java:415) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-457]
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-457]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-457]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

I'm on version 0.5.5-rc of Discord-Webhooks. This is my code:
```java
String nameOrID = ...;
String title = ...;
String description = ...;
String copy = ...;
String copyimg = ...;
Integer color = ...;

WebhookEmbed embed = new WebhookEmbedBuilder()
                    .setTitle(new WebhookEmbed.EmbedTitle(title, ""))
                    .setDescription(description)
                    .setFooter(new WebhookEmbed.EmbedFooter(copy, copyimg))
                    .setColor(color)
                    .build();

            WebhookMessage message = new WebhookMessageBuilder()
                    .addEmbeds(embed)
                    .addFile("af-picture-" + nameOrID + ".png", RenderAPI.imgToByteArray(render.getWrapper().getContent().toBuffered(), "png"))
                    .build();

            Main.getWebhookClient().send(message);
```

RenderAPI.imgToByteArray returns the byte[] of my image.

Am I doing anything wrong, or is this an issue in Discord-webhooks?

**Comment by MinnDevelopment** [comment]
You have an incorrect version of okhttp.

**Comment by stijnb1234** [comment]
```
--- maven-dependency-plugin:2.8:tree (default-cli) @ ActionFoto ---
[INFO] nl.SBDeveloper:ActionFoto:jar:2.7.5
[INFO] +- org.spigotmc:spigot-api:jar:1.16.4-R0.1-SNAPSHOT:provided
[INFO] |  +- commons-lang:commons-lang:jar:2.6:provided
[INFO] |  +- com.google.guava:guava:jar:21.0:provided
[INFO] |  +- com.google.code.gson:gson:jar:2.8.0:provided
[INFO] |  +- net.md-5:bungeecord-chat:jar:1.16-R0.3:provided
[INFO] |  \- org.yaml:snakeyaml:jar:1.26:provided
[INFO] +- com.bergerkiller.bukkit:TrainCarts:jar:1.16.4-v1:provided
[INFO] +- com.bergerkiller.bukkit:BKCommonLib:jar:1.16.4-v2:provided
[INFO] |  \- com.bergerkiller.mountiplex:Mountiplex:jar:2.21:provided
[INFO] |     +- org.ow2.asm:asm:jar:7.0:provided
[INFO] |     +- org.objenesis:objenesis:jar:3.1:provided
[INFO] |     +- org.javassist:javassist:jar:3.27.0-GA:provided
[INFO] |     \- org.apache.maven:maven-project:jar:2.0.6:provided
[INFO] |        +- org.apache.maven:maven-settings:jar:2.0.6:provided
[INFO] |        +- org.apache.maven:maven-profile:jar:2.0.6:provided
[INFO] |        +- org.apache.maven:maven-model:jar:2.0.6:provided
[INFO] |        +- org.apache.maven:maven-artifact-manager:jar:2.0.6:provided
[INFO] |        |  +- org.apache.maven:maven-repository-metadata:jar:2.0.6:provided
[INFO] |        |  \- org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:provided
[INFO] |        +- org.apache.maven:maven-plugin-registry:jar:2.0.6:provided
[INFO] |        +- org.codehaus.plexus:plexus-utils:jar:1.4.1:provided
[INFO] |        +- org.apache.maven:maven-artifact:jar:2.0.6:provided
[INFO] |        \- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:provided
[INFO] |           +- junit:junit:jar:3.8.1:provided
[INFO] |           \- classworlds:classworlds:jar:1.1-alpha-2:provided
[INFO] +- me.paradoxpixel:themepark:jar:2.1.3:system
[INFO] +- org.inventivetalent:mapmanager:jar:1.7.10-SNAPSHOT:provided
[INFO] |  \- org.inventivetalent.packetlistener:api:jar:3.7.8-SNAPSHOT:provided
[INFO] +- com.zaxxer:HikariCP:jar:4.0.1:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.0-alpha1:compile
[INFO] +- club.minnced:discord-webhooks:jar:0.5.5-rc:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO] |  |  \- com.squareup.okio:okio:jar:1.17.2:compile
[INFO] |  \- org.json:json:jar:20180813:compile
[INFO] \- org.jetbrains:annotations:jar:20.1.0:compile
[INFO] ------------------------------------------------------------------------
```

This is my dependency tree. As you can see version 3.14.9 of okhttp is included in my JAR, the same as included in your gradle build file.

**Comment by stijnb1234** [comment]
@MinnDevelopment Do you have any more information for me about this?
