### ISSUE TITLE
No virtual method put(Ljava/lang/String;Ljava/util/Collection;)Lorg/json/JSONObject

### ISSUE THREAD

**Issue by t0pd3v1c3** [MinnDevelopment/discord-webhooks#62]
Hello. I get an error when linking the library:
```java
java.lang.NoSuchMethodError: No virtual method put(Ljava/lang/String;Ljava/util/Collection;)Lorg/json/JSONObject; in class Lorg/json/JSONObject; or its super classes (declaration of 'org.json.JSONObject' appears in /apex/com.android.runtime/javalib/core-libart.jar)
        at club.minnced.discord.webhook.send.WebhookEmbed.toJSONString(WebhookEmbed.java:215)
        at club.minnced.discord.webhook.send.WebhookEmbed.toString(WebhookEmbed.java:190)
        at org.json.JSONStringer.value(JSONStringer.java:261)
        at org.json.JSONArray.writeTo(JSONArray.java:616)
        at org.json.JSONStringer.value(JSONStringer.java:242)
        at org.json.JSONObject.writeTo(JSONObject.java:733)
        at org.json.JSONObject.toString(JSONObject.java:701)
        at club.minnced.discord.webhook.send.WebhookMessage.getBody(WebhookMessage.java:354)
        at club.minnced.discord.webhook.WebhookClient.send(WebhookClient.java:304)
```

**Comment by MinnDevelopment** [comment]
This library requires version [20210307 of org.json:json](https://github.com/MinnDevelopment/discord-webhooks/blob/3a9c6d1c486045c0cd839645e323e332ce96a895/build.gradle.kts#L48) and you are using a different version. I recommend using gradle and adding the required dependency explicitly.
