### ISSUE TITLE
Sending Messages

### ISSUE THREAD

**Issue by ItsAndrexDev** [MinnDevelopment/discord-webhooks#98]
i just have a simple setup that the docs tell me to use and it tells me to send this to the devs:
```
JDA 5.1.0_03aab5c
        MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"components":[],"attachments":[],"author":{"global_name":null,"bot":true,"id":"1280229257544732682","avatar":null,"username":"Spidey Bot","discriminator":"0000"},"flags":0,"type":0,"mention_roles":[],"edited_timestamp":null,"content":"","tts":false,"webhook_id":"1280229257544732682","mentions":[],"guild_id":"1280208329141911582","id":"1280239071096078517","embeds":[],"channel_id":"1280208329141911585","timestamp":"2024-09-02T18:53:00.241000+00:00"}
java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:172) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:117) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:42) ~[DiscordConnector.jar:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[DiscordConnector.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009) [DiscordConnector.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892) [DiscordConnector.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870) [DiscordConnector.jar:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048) [DiscordConnector.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) [DiscordConnector.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) [DiscordConnector.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) [DiscordConnector.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) [DiscordConnector.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [DiscordConnector.jar:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [DiscordConnector.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [DiscordConnector.jar:?]
```
        
        it just spams it a bunch of times

**Comment by MinnDevelopment** [comment]
This is the wrong repository to report JDA issues. Also, there are like 10 duplicates of this on the JDA repo you can look through. It's not a JDA issue but an issue with your usage of JDA in bukkit.
